config/routes.rb
DayreelBackend::Application.routes.draw do

  match ':controller(/:action(/:id))(.:format)'

	root :to => 'home#index'
	match 'register' => 'home#register'
	match 'sign_out' => 'home#sign_out'
	match 'portfolio' => 'portfolio#index'
  get "search" => "bizs#search", as: "search"

  match 'filter' => 'bizs#filter'
  match 'create' => 'bizs#create'

  post "login"  => "home#login"
  match 'sign_error' => 'home#sign_error'

	get "api/auth_with_email"
	get "api/auth_with_token"

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  # skip_before_filter :verify_authenticity_token, :only => [:login]
	protect_from_forgery

	layout 'application'

	before_filter :setSlideItem

	# Start of actions
	def index
		if current_user.nil?
			@user = User.new
		else
			@user = current_user
		end
	end

	def login
		email = params[:user][:email]
		password = params[:user][:password]

		user = User.authenticate_by_email(email, password)

		if user
			update_authentication_token(user, params[:user][:remember_me])
			user.save
			session[:user_id] = user.id
      redirect_to root_url
      # render json: {success: "ok"}
      # flash[:notice] = 'Hi ' + user.name + ', you logged in as ' + user.username
    else
      # respond_to do |format|
      #   format.html {render :login}
      #   format.js {render :layout => false}
      # end

      # flash[:error] = 'Unknown user. Please check your username and password.'
      render json: {error: "Unknown User #{email}. Please check your username and password."}
      # redirect_to root_url
    end
  end

	def register
		user = User.new(params[:user])

		if user.valid?
			update_authentication_token(user, params[:user][:remember_me])
			user.save
			UserMailer.welcome_email(user).deliver
			session[:user_id] = user.id
			flash[:notice] = 'Welcome.'
			redirect_to :root
		else
			# render :action => "new_user"
			redirect_to :root
		end
	end

	# Http put
	def send_password_reset_instructions
		email = params[:user][:email]

		user = User.find_by_email(email)


		if user
			user.password_reset_token = SecureRandom.urlsafe_base64
			user.password_expires_after = 24.hours.from_now
			user.save
			UserMailer.reset_password_email(user).deliver
			flash[:notice] = 'Password instructions have been mailed to you. Please check your inbox.'
			redirect_to :root
		else
			@user = User.new
			# put the previous value back.
			@user.email = params[:user][:email]
			@user.errors[:email] = ' is not a registered user.'
			redirect_to :root
		end
	end

	# HTTP get
	def password_reset
		token = params.first[0]
		@user = User.find_by_password_reset_token(token)

		if @user.nil?
			flash[:error] = 'You have not requested a password reset.'
			redirect_to :root
			return
		end

		if @user.password_expires_after < DateTime.now
			clear_password_reset(@user)
			@user.save
			flash[:error] = 'Password reset has expired. Please request a new password reset.'
			redirect_to :forgot_password
		end
	end

	# HTTP put
	def new_password
		username = params[:user][:username]
		@user = User.find_by_username(username)

		if verify_new_password(params[:user])
			@user.update_attributes(params[:user])
			@user.password = @user.new_password

			if @user.valid?
				clear_password_reset(@user)
				@user.save
				flash[:notice] = 'Your password has been reset. Please sign in with your new password.'
				redirect_to :sign_in
			else
				render :action => "password_reset"
			end
		else
			@user.errors[:new_password] = 'Cannot be blank and must match the password verification.'
			render :action => "password_reset"
		end
	end

	def sign_out
		user = User.find_by_id(session[:user_id])
		if user
			update_authentication_token(user, nil)
			user.save
			session[:user_id] = nil
			flash[:notice] = "You have been signed out."
			# current_user = nil
		end
		redirect_to :root
	end

	# End of actions

	def authenticate_user
		if current_user.nil?
			flash[:error] = 'You must be signed in to view that page.'
			redirect_to :root
		end
	end

	def update_authentication_token(user, remember_me)
		if remember_me.to_i == 1
			# create an authentication token if the user has clicked on remember me
			auth_token = SecureRandom.urlsafe_base64
			user.authentication_token = auth_token
			cookies.permanent[:auth_token] = auth_token
		else # nil or 0
			# if not, clear the token, as the user doesn't want to be remembered.
			user.authentication_token = nil
			cookies.permanent[:auth_token] = nil
			# current_user = nil
		end
	end

	def setSlideItem
		@curSlideItem = 'home'
	end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<div id="sb-site">
    <div class="clearfix">
        <div class="container noPadding-middle ">

            <!--<div class="row">-->
            <div class="col-lg-12 col-md-8 col-md-push-4 col-lg-push-0 noPadding-desktop noPadding-middle noPadding-small leftPadding">
                <div class="menuBlocks clearfix">
                    <div class="col-custom col-md-4 col-sm-4 col-xs-4" >
                         <a href="#" class="topMenuLink">
                            Find Businesses
                            <span class="menuDivider">|</span>
                        </a>
                    </div>
                    <div class="col-custom col-md-4 col-sm-4 col-xs-4" >
                        <a href="#" class="topMenuLink">
                            Book Online
                            <span class="menuDivider">|</span>
                        </a>
                    </div>
                    <div class="col-custom col-md-4 col-sm-4 col-xs-4" >
                        <a href="#" class="topMenuLink" >
                            Share Referrals
                        </a>
                    </div>
                </div>
                <div class="searchBlocks clearfix">
                  <%= form_tag(search_url, method:'get', class:'form-horizontal' ) do %>
                      <div class="col-lg-9 col-md-9 col-sm-9 col-xs-12 noPadding-desktop noPadding-middle noPadding-small searchInputWrapper">
                        <%= text_field_tag :key, nil,:class => 'dayreel-input', :placeholder => 'What are you looking for? Hair, Lawn care, Cleaners...'%>
                      </div>
                      <div class="col-lg-3 col-md-3 col-sm-3 col-xs-12 noPadding-desktop searchOrangeBlock">
                        <div class="whiteTriangle  pull-left hidden-xs"></div>
                        <a href="javascript:void(0);" class="pull-left searchLink">Kansas City?</a>
                        <%= button_tag 'button', :type => 'submit', :class => 'searchBtn pull-right'%>
                      </div>
                  <% end %>
                </div>
                <div class="videoBlocks clearfix">
                    <div class="col-lg-6 col-md-4 col-sm-12 col-xs-12 noPadding-desktop noPadding-small">
                        <div class="videoWrapper">
                            <div class="howItWorks">How it works</div>
                            <%= image_tag "videoThumb.png", alt: "" %>
                        </div>
                    </div>
                    <div class="col-lg-6 col-md-8 col-sm-12 col-xs-12 noPadding-desktop noPadding-small">
                        <ul class="homeList">
                            <li class="homeList-li">
                                <span class="homeList-round pull-left"></span>
                                <div class="pull-left homeList-text">
                                    <div class="homeList-bigText">Visit any online business or search DayReel. </div>
                                    <div class="homeList-smallText">Find your favorite business? Click your Reel (wheel logo) button.</div>
                                </div>
                            </li>
                            <li class="homeList-li">
                                <span class="homeList-round pull-left"></span>
                                <div class="pull-left homeList-text">
                                    <div class="homeList-bigText">Clicking the Reel (wheel logo) button saves</div>
                                    <div class="homeList-smallText">the business to My Portfolio.</div>
                                </div>
                            </li>
                            <li class="homeList-li">
                                <span class="homeList-round pull-left"></span>
                                <div class="pull-left homeList-text">
                                    <div class="homeList-bigText">Collect all of your favorite businesses in one location. </div>
                                    <div class="homeList-smallText">You can organize them, share them, and book online.</div>
                                </div>
                            </li>
                        </ul>
                      <a href="ex.crx" class="btnInstall btn">Install Reel Button</a>
                    </div>
                </div>
            </div>
            <div class=" col-lg-12 col-md-4 col-md-pull-8 col-lg-pull-0 portfolio-blocks">
                <div class="portfolio-header" >
                    Start Building Your Personal Portfolio!
                </div>
                <div class="portfolio-item-slide clearfix" >
                    <div class="col-custom col-sm-6  portfolio-item-wrapper">
                        <div class="col-portfolio-item">
                            <a href="#">
                                <span class="portfolio-name">Donna</span>
                                <span class="portfolio-item donna"></span>    
                            </a>
                        </div>
                    </div>
                    <div class="col-custom col-sm-6 portfolio-item-wrapper"> 
                        <div class="col-portfolio-item">
                            <a href="#">
                                <span class="portfolio-name">Home</span>
                                <span class="portfolio-item home"></span> 
                            </a>
                        </div>
                    </div>
                    <div class="col-custom col-sm-6 portfolio-item-wrapper">
                        <div class="col-portfolio-item">
                            <a href="#">
                                <span class="portfolio-name">Ethan</span>
                                <span class="portfolio-item ethan"></span>
                            </a>
                        </div>
                    </div>
                    <div class="col-custom col-sm-6 portfolio-item-wrapper">
                        <div class="col-portfolio-item">
                            <a href="#">
                                <span class="portfolio-name">Grant</span>
                                <span class="portfolio-item grant"></span>
                            </a>
                        </div>
                    </div>
                    <div class="col-custom col-sm-6 portfolio-item-wrapper">
                        <div class="col-portfolio-item">
                            <a href="#">
                                <span class="portfolio-name">Lance</span>
                                <span class="portfolio-item lance"></span>
                            </a>
                        </div>
                    </div>
                    <div class="col-custom col-sm-6 portfolio-item-wrapper">
                        <div class="col-portfolio-item">
                            <a href="#">
                                <span class="portfolio-name">Riley</span>
                                <span class="portfolio-item riley"></span>
                            </a>
                        </div>
                    </div>
                    <div class="col-custom col-sm-6 portfolio-item-wrapper">
                        <div class="col-portfolio-item">
                            <a href="#">
                                <span class="portfolio-name">Car</span>
                                <span class="portfolio-item car"></span>
                            </a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div id="push"></div>
    

app/views/home/sign_error.html.erb
<div id="sb-site">
<div class="container">
    <div class="login-error clearfix">
        <div class="alert alert-danger">
            <%= flash[:error] %>
        </div>
        <div class="pull-right clearfix">
            <a type="button" href="/" class="btn btn-orange">back</a>
            <a type="button"  data-target="#signinModal" data-toggle="modal" class="btn btn-orange">login</a>
        </div>
    </div>
</div>
<style>
  .login-error{
      margin:20px 0px
  }
  .alert-danger{
      height:200px;
  }
</style>